name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  http: ^1.6.0
  intl: ^0.20.2
  provider: ^6.1.5+1
  fl_chart: ^0.70.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/players.json
    - assets/data/player_histories.json
    - assets/data/tt_players.json
    - assets/data/tt_player_histories.json
    - assets/data/football_national_teams.json
    - assets/data/basketball_clubs.json
